CREATE TABLE VC_CLOSET (
  ID INT NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  BODY_POSITION_OVERLAP BOOLEAN NOT NULL DEFAULT FALSE,
  USER_ID INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (NAME),
  CONSTRAINT fk_VC_CLOSET_USER
      FOREIGN KEY(USER_ID)
      REFERENCES VC_USER(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);

CREATE SEQUENCE VC_CLOSET_SEQ INCREMENT BY 1;

CREATE TABLE VC_CLOSET_CLOTHING (
  ID INT NOT NULL,
  CLOSET_ID INT NOT NULL,
  CLOTHING_ID INT NOT NULL,
  ZINDEX INT NOT NULL DEFAULT 0,
  UNIQUE (CLOSET_ID, CLOTHING_ID, ZINDEX),
  PRIMARY KEY (ID),
  CONSTRAINT fk_VC_CLOSET_CLOTHING_CLOSET
      FOREIGN KEY(CLOSET_ID)
      REFERENCES VC_CLOSET(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT fk_VC_CLOSET_CLOTHING_CLOTHING
      FOREIGN KEY(CLOTHING_ID)
      REFERENCES VC_CLOTHING(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);
      
  CREATE SEQUENCE VC_CLOSET_CLOTHING_SEQ INCREMENT BY 1;

