CREATE TABLE IF NOT EXISTS VC_SECTOR (
  ID INT NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  OPTIONAL BOOLEAN NOT NULL,
  TOP_MOST BOOL NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS VC_SECTOR_BODY_POSITION (
  SECTOR_ID INT NOT NULL,
  BODY_POSITION VARCHAR(20) NOT NULL,
  UNIQUE (SECTOR_ID, BODY_POSITION),
  CONSTRAINT fk_VC_SECTOR_BODY_POSITION
    FOREIGN KEY(SECTOR_ID)
    REFERENCES VC_SECTOR(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS VC_USER (
    ID INT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,    
    PRIMARY KEY(ID));

CREATE SEQUENCE IF NOT EXISTS VC_USER_SEQ INCREMENT 1; 
  
CREATE TABLE IF NOT EXISTS VC_CLOTHING (
    ID INT NOT NULL,
    NAME VARCHAR(120) NOT NULL,
    PICTURE BYTEA NULL,
    FANCY BOOLEAN NOT NULL DEFAULT FALSE,
    USAGE_COUNT INT NOT NULL,
    RATING INT NOT NULL DEFAULT 0,
    SECTOR_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT fk_VC_CLOTHING_SECTOR
        FOREIGN KEY(SECTOR_ID)
        REFERENCES VC_SECTOR(ID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_VC_CLOTHING_USER
        FOREIGN KEY(USER_ID)
        REFERENCES VC_USER(ID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION);
        
CREATE SEQUENCE IF NOT EXISTS VC_CLOTHING_SEQ INCREMENT 1;
