ALTER TABLE VC_USER ADD COLUMN ROLE VARCHAR(20);
UPDATE VC_USER SET ROLE = 'USER';
ALTER TABLE VC_USER ALTER COLUMN ROLE SET NOT NULL;

ALTER TABLE VC_USER ADD COLUMN ACTIVE BOOL NOT NULL DEFAULT TRUE;
ALTER TABLE VC_USER ADD COLUMN PASSWORD_EXPIRATION_DATE TIMESTAMP;
